# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extrapolation_emerg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExtrapolationSetting(object):
    def setupUi(self, ExtrapolationSetting):
        ExtrapolationSetting.setObjectName("ExtrapolationSetting")
        ExtrapolationSetting.resize(1033, 842)
        self.method_frame = QtWidgets.QWidget(ExtrapolationSetting)
        self.method_frame.setObjectName("method_frame")
        self.w_tittle = QtWidgets.QLabel(self.method_frame)
        self.w_tittle.setGeometry(QtCore.QRect(370, 0, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.w_tittle.setFont(font)
        self.w_tittle.setObjectName("w_tittle")
        self.save_button = QtWidgets.QPushButton(self.method_frame)
        self.save_button.setGeometry(QtCore.QRect(590, 800, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.backg_1 = QtWidgets.QLabel(self.method_frame)
        self.backg_1.setGeometry(QtCore.QRect(10, 40, 1011, 351))
        self.backg_1.setStyleSheet("background-color: rgb(255, 224, 185);")
        self.backg_1.setText("")
        self.backg_1.setObjectName("backg_1")
        self.knn_descrip = QtWidgets.QTextBrowser(self.method_frame)
        self.knn_descrip.setGeometry(QtCore.QRect(30, 80, 981, 301))
        self.knn_descrip.setObjectName("knn_descrip")
        self.backg_2 = QtWidgets.QLabel(self.method_frame)
        self.backg_2.setGeometry(QtCore.QRect(10, 420, 1011, 371))
        self.backg_2.setStyleSheet("background-color: rgb(215, 213, 255)")
        self.backg_2.setText("")
        self.backg_2.setObjectName("backg_2")
        self.stratified_descrip = QtWidgets.QTextBrowser(self.method_frame)
        self.stratified_descrip.setGeometry(QtCore.QRect(30, 460, 981, 321))
        self.stratified_descrip.setObjectName("stratified_descrip")
        self.knn_check = QtWidgets.QCheckBox(self.method_frame)
        self.knn_check.setGeometry(QtCore.QRect(30, 50, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.knn_check.setFont(font)
        self.knn_check.setObjectName("knn_check")
        self.stratified_check = QtWidgets.QCheckBox(self.method_frame)
        self.stratified_check.setGeometry(QtCore.QRect(30, 430, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stratified_check.setFont(font)
        self.stratified_check.setObjectName("stratified_check")
        self.load_buton = QtWidgets.QPushButton(self.method_frame)
        self.load_buton.setGeometry(QtCore.QRect(300, 800, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.load_buton.setFont(font)
        self.load_buton.setObjectName("load_buton")
        self.backg_2.raise_()
        self.backg_1.raise_()
        self.w_tittle.raise_()
        self.save_button.raise_()
        self.knn_descrip.raise_()
        self.stratified_descrip.raise_()
        self.knn_check.raise_()
        self.stratified_check.raise_()
        self.load_buton.raise_()
        ExtrapolationSetting.setCentralWidget(self.method_frame)

        self.retranslateUi(ExtrapolationSetting)
        QtCore.QMetaObject.connectSlotsByName(ExtrapolationSetting)

    def retranslateUi(self, ExtrapolationSetting):
        _translate = QtCore.QCoreApplication.translate
        ExtrapolationSetting.setWindowTitle(_translate("ExtrapolationSetting", "MainWindow"))
        self.w_tittle.setText(_translate("ExtrapolationSetting", "Setting Extrapolation Method"))
        self.save_button.setText(_translate("ExtrapolationSetting", "Save and continue"))
        self.knn_descrip.setHtml(_translate("ExtrapolationSetting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This method considers the distance to the </span><span style=\" font-size:10pt; font-weight:600;\">K nearest neighbors</span><span style=\" font-size:10pt;\"> and uses </span><span style=\" font-size:10pt; font-weight:600;\">soft voting</span><span style=\" font-size:10pt;\">, meaning that closer neighbors carry more weight in determining the final class. It is based on the assumption that nearby buildings are more likely to share similar characteristics and applies </span><span style=\" font-size:10pt; font-weight:600;\">inverse kernel weighting</span><span style=\" font-size:10pt;\"> to reflect this relationship.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The process begins with an </span><span style=\" font-size:10pt; font-weight:600;\">initial sample representing 10% of the population</span><span style=\" font-size:10pt;\">. Building information can be provided either by uploading a CSV file or by using the built-in </span><span style=\" font-size:10pt; font-weight:600;\">deep learning model</span><span style=\" font-size:10pt;\"> integrated into the tool.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Convergence</span><span style=\" font-size:10pt;\"> is evaluated based on the stability of the variable of interest—in this case, </span><span style=\" font-size:10pt; font-weight:600;\">building taxonomies</span><span style=\" font-size:10pt;\">. If the distribution of taxonomies changes by no more than </span><span style=\" font-size:10pt; font-weight:600;\">5%</span><span style=\" font-size:10pt;\"> in the subsequent iteration, convergence is assumed. Otherwise, the sample size is incrementally increased by </span><span style=\" font-size:10pt; font-weight:600;\">5%</span><span style=\" font-size:10pt;\"> in each iteration (e.g., 1st iteration = 10%, 2nd iteration = 15%, and so on) until convergence is reached.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Once convergence is achieved, the </span><span style=\" font-size:10pt; font-weight:600;\">sampling stage is complete</span><span style=\" font-size:10pt;\">, and the </span><span style=\" font-size:10pt; font-weight:600;\">extrapolation process</span><span style=\" font-size:10pt;\"> begins. At this stage, the tool analyzes the buildings of interest, calculates the </span><span style=\" font-size:10pt; font-weight:600;\">geodesic distance</span><span style=\" font-size:10pt;\"> to all available sampled buildings, and selects the 10 closest ones to estimate a </span><span style=\" font-size:10pt; font-weight:600;\">probabilistic distribution of likely taxonomies</span><span style=\" font-size:10pt;\">.</span></p></body></html>"))
        self.stratified_descrip.setHtml(_translate("ExtrapolationSetting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This method uses a </span><span style=\" font-size:10pt; font-weight:600;\">stratified sampling process based on Scheaffer et al. (1986)</span><span style=\" font-size:10pt;\">, aimed at estimating the distribution of building taxonomy classes. It begins by calculating a </span><span style=\" font-size:10pt; font-weight:600;\">pilot sample size</span><span style=\" font-size:10pt;\"> using a conservative formula that assumes maximum uncertainty in class proportions. Based on this pilot sample, the method estimates class proportions.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The process adheres to the principles of stratified sampling, ensuring that each class (or stratum) is proportionally represented according to its estimated frequency and variance. Users can iteratively upload </span><span style=\" font-size:10pt; font-weight:600;\">new</span><span style=\" font-size:10pt;\"> </span><span style=\" font-size:10pt; font-weight:600;\">CSV files (manually)</span><span style=\" font-size:10pt;\"> or use the built-in </span><span style=\" font-size:10pt; font-weight:600;\">deep learning model</span><span style=\" font-size:10pt;\"> to classify images and expand the sample—</span><span style=\" font-size:10pt; font-weight:600;\">increasing by a step value provided by the user (5% by default) of the population per iteration</span><span style=\" font-size:10pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">After each iteration, the method checks whether the estimated class proportions have </span><span style=\" font-size:10pt; font-weight:600;\">converged</span><span style=\" font-size:10pt;\">, meaning they remain stable across samples. If convergence is achieved, the process stops; otherwise, sampling continues, ensuring both </span><span style=\" font-size:10pt; font-weight:600;\">statistical robustness</span><span style=\" font-size:10pt;\"> and </span><span style=\" font-size:10pt; font-weight:600;\">data efficiency</span><span style=\" font-size:10pt;\">.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Once convergence is reached, the </span><span style=\" font-size:10pt; font-weight:600;\">assignment process</span><span style=\" font-size:10pt;\"> begins. This step uses a </span><span style=\" font-size:10pt; font-weight:600;\">hierarchical fallback strategy</span><span style=\" font-size:10pt;\"> that depends on the availability of information. The method prioritizes the use of </span><span style=\" font-size:10pt; font-weight:600;\">specific local data</span><span style=\" font-size:10pt;\"> where available, and progressively falls back to </span><span style=\" font-size:10pt; font-weight:600;\">more general or global information</span><span style=\" font-size:10pt;\"> when needed, ensuring the most accurate classification possible based on the data at hand.</span></p></body></html>"))
        self.knn_check.setText(_translate("ExtrapolationSetting", "K-NN with Soft Voting"))
        self.stratified_check.setText(_translate("ExtrapolationSetting", "Stratified Sampling"))
        self.load_buton.setText(_translate("ExtrapolationSetting", "Load files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ExtrapolationSetting = QtWidgets.QMainWindow()
    ui = Ui_ExtrapolationSetting()
    ui.setupUi(ExtrapolationSetting)
    ExtrapolationSetting.show()
    sys.exit(app.exec_())
