# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSV_image_angle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GSV_angle_setting(object):
    def setupUi(self, GSV_angle_setting):
        GSV_angle_setting.setObjectName("GSV_angle_setting")
        GSV_angle_setting.resize(651, 866)
        self.gsv_angle_frame = QtWidgets.QWidget(GSV_angle_setting)
        self.gsv_angle_frame.setObjectName("gsv_angle_frame")
        self.save_button_gsv = QtWidgets.QPushButton(self.gsv_angle_frame)
        self.save_button_gsv.setGeometry(QtCore.QRect(240, 830, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_button_gsv.setFont(font)
        self.save_button_gsv.setObjectName("save_button_gsv")
        self.backg_1 = QtWidgets.QLabel(self.gsv_angle_frame)
        self.backg_1.setGeometry(QtCore.QRect(10, 10, 631, 811))
        self.backg_1.setStyleSheet("background-color: rgb(255, 215, 255);")
        self.backg_1.setText("")
        self.backg_1.setObjectName("backg_1")
        self.gsv_label = QtWidgets.QLabel(self.gsv_angle_frame)
        self.gsv_label.setGeometry(QtCore.QRect(250, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.gsv_label.setFont(font)
        self.gsv_label.setObjectName("gsv_label")
        self.pitch_label = QtWidgets.QLabel(self.gsv_angle_frame)
        self.pitch_label.setGeometry(QtCore.QRect(20, 39, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pitch_label.setFont(font)
        self.pitch_label.setObjectName("pitch_label")
        self.pitch_img = QtWidgets.QLabel(self.gsv_angle_frame)
        self.pitch_img.setGeometry(QtCore.QRect(20, 170, 611, 361))
        self.pitch_img.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pitch_img.setObjectName("pitch_img")
        self.pitch_descrip = QtWidgets.QTextBrowser(self.gsv_angle_frame)
        self.pitch_descrip.setGeometry(QtCore.QRect(20, 80, 611, 81))
        self.pitch_descrip.setObjectName("pitch_descrip")
        self.pitch_value = QtWidgets.QSpinBox(self.gsv_angle_frame)
        self.pitch_value.setGeometry(QtCore.QRect(80, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pitch_value.setFont(font)
        self.pitch_value.setMaximum(60)
        self.pitch_value.setProperty("value", 5)
        self.pitch_value.setObjectName("pitch_value")
        self.heading_label = QtWidgets.QLabel(self.gsv_angle_frame)
        self.heading_label.setGeometry(QtCore.QRect(20, 539, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.heading_label.setFont(font)
        self.heading_label.setObjectName("heading_label")
        self.heading_value = QtWidgets.QSpinBox(self.gsv_angle_frame)
        self.heading_value.setGeometry(QtCore.QRect(110, 540, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.heading_value.setFont(font)
        self.heading_value.setMinimum(0)
        self.heading_value.setMaximum(360)
        self.heading_value.setProperty("value", 0)
        self.heading_value.setObjectName("heading_value")
        self.heading_descrip = QtWidgets.QTextBrowser(self.gsv_angle_frame)
        self.heading_descrip.setGeometry(QtCore.QRect(20, 580, 611, 81))
        self.heading_descrip.setObjectName("heading_descrip")
        self.fov_label = QtWidgets.QLabel(self.gsv_angle_frame)
        self.fov_label.setGeometry(QtCore.QRect(20, 670, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.fov_label.setFont(font)
        self.fov_label.setObjectName("fov_label")
        self.fov_value = QtWidgets.QSpinBox(self.gsv_angle_frame)
        self.fov_value.setGeometry(QtCore.QRect(70, 670, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fov_value.setFont(font)
        self.fov_value.setMinimum(1)
        self.fov_value.setMaximum(120)
        self.fov_value.setProperty("value", 120)
        self.fov_value.setObjectName("fov_value")
        self.fov_descrip = QtWidgets.QTextBrowser(self.gsv_angle_frame)
        self.fov_descrip.setGeometry(QtCore.QRect(20, 710, 611, 101))
        self.fov_descrip.setObjectName("fov_descrip")
        GSV_angle_setting.setCentralWidget(self.gsv_angle_frame)

        self.retranslateUi(GSV_angle_setting)
        QtCore.QMetaObject.connectSlotsByName(GSV_angle_setting)

    def retranslateUi(self, GSV_angle_setting):
        _translate = QtCore.QCoreApplication.translate
        GSV_angle_setting.setWindowTitle(_translate("GSV_angle_setting", "MainWindow"))
        self.save_button_gsv.setText(_translate("GSV_angle_setting", "Save and continue"))
        self.gsv_label.setText(_translate("GSV_angle_setting", "GSV image parameters"))
        self.pitch_label.setText(_translate("GSV_angle_setting", "Pitch:"))
        self.pitch_img.setText(_translate("GSV_angle_setting", "TextLabel"))
        self.pitch_descrip.setHtml(_translate("GSV_angle_setting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Vertical camera angle that controls the inclination of the camera, allowing a full view of tall buildings. This angle is limited between </span><span style=\" font-size:10pt; font-weight:600;\">0° and 60°</span><span style=\" font-size:10pt;\">, with </span><span style=\" font-size:10pt; font-weight:600;\">5° as the default value</span><span style=\" font-size:10pt;\">.</span></p></body></html>"))
        self.heading_label.setText(_translate("GSV_angle_setting", "Heading:"))
        self.heading_descrip.setHtml(_translate("GSV_angle_setting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">It is </span><span style=\" font-size:10pt; font-weight:600;\">horizontal camera angle</span><span style=\" font-size:10pt;\"> controls the direction of the camera, even allowing the view of a building on the opposite side of the street (180°). This angle is limited between </span><span style=\" font-size:10pt; font-weight:600;\">0° and 360°</span><span style=\" font-size:10pt;\">, with </span><span style=\" font-size:10pt; font-weight:600;\">0° as the default value</span><span style=\" font-size:10pt;\">.</span></p></body></html>"))
        self.fov_label.setText(_translate("GSV_angle_setting", "FOV:"))
        self.fov_descrip.setHtml(_translate("GSV_angle_setting", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The </span><span style=\" font-size:10pt; font-weight:600;\">field of view</span><span style=\" font-size:10pt;\"> controls the zoom of the camera. Smaller values </span><span style=\" font-size:10pt; font-weight:600;\">zoom in</span><span style=\" font-size:10pt;\">, while larger values </span><span style=\" font-size:10pt; font-weight:600;\">zoom out</span><span style=\" font-size:10pt;\">. By default, this value is set to </span><span style=\" font-size:10pt; font-weight:600;\">120</span><span style=\" font-size:10pt;\">, which is the maximum allowed. This is useful for creating a natural zoom effect without losing too much resolution for distant building images</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GSV_angle_setting = QtWidgets.QMainWindow()
    ui = Ui_GSV_angle_setting()
    ui.setupUi(GSV_angle_setting)
    GSV_angle_setting.show()
    sys.exit(app.exec_())
